vaadin.launch-browser=true
spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/Zlagoda
spring.datasource.username=postgres
spring.datasource.password=Sand5Man9
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=HikariCP
